export const concertos = [
  {
    Title: 'Academic Festival Rag for Piano and Wind Ensemble',
    Category: 'Concertos',
    Forces: 'Piano and Wind Ensemble',
    dateOfComposition: '2012',
    Duration: '10.5 minutes',
    Score: '61 pp.',
    partOrParts: '163 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/academic-festival-rag-for-piano-and-wind-ensemble',
    catalogueNo: '001'
  },
  {
    Title: 'Academic Festival Rag for Two Pianos',
    Category: 'Concertos',
    Forces: 'Two Pianos',
    dateOfComposition: '2012',
    Duration: '10.5 minutes',
    Score: '32 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/academic-festival-rag-for-two-pianos',
    catalogueNo: '002'
  },
  {
    Title: 'Introduction and Ragtime for Clarinet in B-flat and Piano',
    Category: 'Concertos',
    Forces: 'Clarinet in B-flat and Piano',
    dateOfComposition: '2012',
    Duration: '9.25 minutes',
    Score: '19 pp.',
    partOrParts: '7 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/introduction-and-rag-for-clarinet-and-orchestra-arranged-for-clarinet-and-piano',
    catalogueNo: '004'
  }
]

export const orchestral = [
  {
    Title: 'Franklin Portrait: Preamble for Orchestra',
    Category: 'Orchestra',
    Forces: 'Orchestra',
    dateOfComposition: '2006',
    Duration: '5 minutes',
    Score: '22 pp.',
    partOrParts: '57 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/franklin-portrait-preamble-for-orchestra',
    catalogueNo: '007'
  }
]

export const orchestraNarration = [
  {
    Title: 'Le Tombeau de Saint-Saëns',
    Category: 'Orchestra with Narration',
    Forces: 'Orchestra and Narrator',
    dateOfComposition: '2003',
    Duration: '23.5 minutes',
    Score: '115 pp.',
    partOrParts: '336 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-orchestra-and-narrator',
    catalogueNo: '010'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut)',
    Category: 'Orchestra with Narration',
    Forces: 'Orchestra and Narrator',
    dateOfComposition: '2008',
    Duration: '13 minutes',
    Score: '45 pp.',
    partOrParts: '88 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut-for-orchestra-and-narrator',
    catalogueNo: '011'
  }
]

export const concertBandNarration = [
  {
    Title: 'Little Red Riding Hood or Ladle Rat Rotten Hut for Concert Band and Narrator',
    Category: 'Concert Band with Narration',
    Forces: 'Concert Band and Narrator',
    dateOfComposition: '2009',
    Duration: '12.5 minutes',
    Score: '51 pp.',
    partOrParts: '89 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/littleredridinghoodforconcertbandnarrator',
    catalogueNo: '014'
  }
]

export const chamberEnsemblesNarration = [
  {
    Title: 'Le Tombeau de Saint-Saëns for Woodwind Quintet and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Woodwind Quintet and Narrator',
    dateOfComposition: '2013',
    Duration: '18.5 minutes',
    Score: '43 pp.',
    partOrParts: '91 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-woodwind-quintet-and-narrator',
    catalogueNo: '020'
  },
  {
    Title: 'Le Tombeau de Saint-Saëns for Marimba, Clarinet in B flat, Piano and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Marimba, Clarinet in B-flat, Piano, and Narrator',
    dateOfComposition: '2020',
    Duration: '18.5 minutes',
    Score: '36 pp.',
    partOrParts: '29 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-marimba-clarinet-in-b-flat-piano-and-narrator',
    catalogueNo: '020b'
  },
  {
    Title: 'Le Tombeau de Saint-Saëns for Piano Four-Hands and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Piano Four-Hands and Narrator',
    dateOfComposition: '2020',
    Duration: '18.5 minutes',
    Score: '42 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI excerpts for nos. 1, 4, 10, and 13',
    URL: 'https://www.christopherkies.com/store/letombeaudesaintsaenspianofourhandsandnarrator',
    catalogueNo: '020c'
  },
  {
    Title: 'Le Tombeau de Saint-Saëns for Brass Quintet and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Brass Quintet and Narrator',
    dateOfComposition: '2002, rev. 2009',
    Duration: '18.5 minutes',
    Score: '46 pp.',
    partOrParts: '83 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-brass-quintet-and-narrator',
    catalogueNo: '021'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Piano Four-Hands and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Piano Four-Hands and Narrator',
    dateOfComposition: '2007; arr. for piano four-hands in 2012',
    Duration: '12.5 minutes',
    Score: '27 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI (no narrator)',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut-for-piano-four-hands-and-narrator',
    catalogueNo: '022 / 053'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Oboe, Bassoon, Piano, and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Oboe, Bassoon, Piano, and Narrator',
    dateOfComposition: '2007',
    Duration: '12.5 minutes',
    Score: '25 pp.',
    partOrParts: '10 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Recording',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut-for-oboe-bassoon-and-piano',
    catalogueNo: '023'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Flute, Bassoon, Piano and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Flute, Bassoon, Piano, and Narrator',
    dateOfComposition: '2007',
    Duration: '12.5 minutes',
    Score: '25 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-for-flute-bassoon-piano-and-narrator',
    catalogueNo: '024'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Clarinet in B Flat, Cello, Piano, and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Clarinet in B-flat, Cello, Piano, and Narrator',
    dateOfComposition: '2007',
    Duration: '12.5 minutes',
    Score: '27 pp.',
    partOrParts: '11 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut',
    catalogueNo: '026'
  },
  {
    Title: 'Old Business for Piano, Contrabass, Drum Set, and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Piano, Contrabass, Drum Set, and Narrator',
    dateOfComposition: '2012',
    Duration: '11 minutes',
    Score: '68 pp.',
    partOrParts: '16 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/old-business',
    catalogueNo: '027'
  }
]

export const chamberMusicDoubleReed = [
  {
    Title: 'Arietta for Bassoon Quartet',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Four Bassoons',
    dateOfComposition: '2007',
    Duration: '4 minutes',
    Score: '7 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/arietta-for-bassoon-quartet',
    catalogueNo: '028'
  },
  {
    Title: 'Four Bachtatonic/Rocktatonic Inventions for Oboe, Clarinet in B flat and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Clarinet in B-flat, and Piano',
    dateOfComposition: '2018',
    Duration: '10.5 minutes',
    Score: '37 pp.',
    partOrParts: '16 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/four-bachtatonicrocktatonic-inventions-for-oboe-clarinet-in-b-flat-and-piano',
    catalogueNo: '029'
  },
  {
    Title: 'In-Two-itive Dances for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2002',
    Duration: '12 minutes',
    Score: '44 pp.',
    partOrParts: '19 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/e0lteemsvsyzt2ybrqa7q3hk417352',
    catalogueNo: '030'
  },
  {
    Title: 'Nobody Knows for Oboe and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe and Piano',
    dateOfComposition: '2013',
    Duration: '6 minutes',
    Score: '23 pp.',
    partOrParts: '5 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/nobody-knows-for-oboe-and-piano',
    catalogueNo: '032'
  },
  {
    Title: 'The Octatonic Rag for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2010',
    Duration: '4.5 minutes',
    Score: '16 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/octatonic-rag-for-oboe-bassoon-and-piano',
    catalogueNo: '034b'
  },
  {
    Title: 'Sieben Lieder ohne Wörter (aus Des Knaben Wunderhorn) for Bassoon and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Bassoon and Piano',
    dateOfComposition: '2014',
    Duration: '14 minutes',
    Score: '34 pp.',
    partOrParts: '12 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/sieben-lieder-ohne-worter-aus-des-knaben-wunderhorn-for-bassoon-and-piano',
    catalogueNo: '043'
  },
  {
    Title: 'Sonata for Bassoon and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Bassoon and Piano',
    dateOfComposition: '2003; revised 2007',
    Duration: '13.5 minutes',
    Score: '30 pp.',
    partOrParts: '10 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/sonata-for-bassoon-and-piano',
    catalogueNo: '044'
  },
  {
    Title: 'Take the Love, This Can\'t Be the A Train for Bassoon Quartet',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Four Bassoons',
    dateOfComposition: '2010',
    Duration: '4.25 minutes',
    Score: '14 pp.',
    partOrParts: '12 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/take-the-love-this-cant-be-the-a-train-for-bassoon-quartet',
    catalogueNo: '045'
  },
  {
    Title: 'Take the Love, This Can\'t Be the A Train for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2010',
    Duration: '4.5 minutes',
    Score: '15 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/take-the-love-this-cant-be-the-a-train',
    catalogueNo: '046'
  },
  {
    Title: 'Taylor Fanfare for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2013',
    Duration: '4.5 minutes',
    Score: '17 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/taylor-fanfare-for-oboe-bassoon-and-piano',
    catalogueNo: '047'
  },
  {
    Title: 'Variations on Country Gardens for Woodwind Quartet',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2005 and 2012',
    Duration: '3 minutes',
    Score: '10 pp.',
    partOrParts: '12 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/variations-on-country-gardens-for-woodwind-quartet',
    catalogueNo: '048'
  },
  {
    Title: 'Variations on Country Gardens for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2005 and 2012',
    Duration: '3 minutes',
    Score: '13 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/variations-on-country-gardens',
    catalogueNo: '049'
  }
]

export const otherInstrumental = [
  {
    Title: 'Flight of the Bungled G for Harpsichord',
    Category: 'Other Instrumental Works',
    Forces: 'Harpsichord',
    dateOfComposition: '2001',
    Duration: '2.5 minutes',
    Score: '8 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/flight-of-the-bungled-g-for-harpsicord',
    catalogueNo: '144'
  },
  {
    Title: 'Four Bachtatonic/Rocktatonic Inventions for Marimba, Clarinet in B Flat, and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'Marimba, Clarinet in B-flat, and Piano',
    dateOfComposition: '2018',
    Duration: '11 minutes',
    Score: '35 pp.',
    partOrParts: '16',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/four-bachtatonicrocktatonic-inventions-for-marimba-clarinet-in-b-flat-and-piano',
    catalogueNo: '056'
  },
  {
    Title: 'Ragtime Reflections for Flute and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'Flute and Piano',
    dateOfComposition: '2013',
    Duration: 'not given',
    Score: '13 pp.',
    partOrParts: '4',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/ragtime-reflections-flute-and-piano',
    catalogueNo: '061'
  },
  {
    Title: 'Take the Love, This Can\'t be the A Train for Clarinet in B Flat and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'Clarinet in B-flat and Piano',
    dateOfComposition: '2010; revised 2011',
    Duration: '4.5 minutes',
    Score: '12 pp.',
    partOrParts: '3',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/take-the-love-this-cant-be-the-a-train-for-clarinet-in-b-flat-and-piano',
    catalogueNo: '063'
  },
  {
    Title: 'Taylor Fanfare for String Quartet and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'String Quartet and Piano',
    dateOfComposition: 'orig. 2013; arr. 2017',
    Duration: '4.5 minutes',
    Score: '24 pp.',
    partOrParts: '12',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/taylor-fanfare-for-string-quartet-and-piano',
    catalogueNo: '066'
  }
]

export const pianoSolo = [
  {
    Title: 'Eight Ragtime Pieces for Piano',
    Category: 'Piano Solo',
    Forces: 'Piano',
    dateOfComposition: '1975-1993',
    Duration: 'ca. 28 minutes',
    Score: '81 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performances',
    URL: 'https://www.christopherkies.com/store/eight-ragtime-pieces-for-piano',
    catalogueNo: '051'
  },
  {
    Title: 'Cadenzas to W. A. Mozart\'s Piano Concerto, K. 467',
    Category: 'Piano Solo',
    Forces: 'Piano',
    dateOfComposition: '1980; revised 2021',
    Duration: 'not given',
    Score: '11 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/cadenzas-to-mozarts-piano-concerto-k-467',
    catalogueNo: '146'
  }
]

export const pianoFourHands = [
  {
    Title: 'Flight of the Bungled G for Piano Four-Hands',
    Category: 'Piano Four-Hands',
    Forces: 'One Piano, Four-Hands',
    dateOfComposition: 'orig. 2001; arr. 2018',
    Duration: '2.5 minutes',
    Score: '4 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/flight-of-the-bungled-g-for-piano-four-hands',
    catalogueNo: '145'
  },
  {
    Title: 'Four Four-Handed Complements',
    Category: 'Piano Four-Hands',
    Forces: 'One Piano, Four-Hands',
    dateOfComposition: '2007; revised 2013',
    Duration: 'ca. 15 minutes',
    Score: '54 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/four-four-handed-complements',
    catalogueNo: '052'
  },
  {
    Title: 'Le Tombeau de Saint-Saëns for Piano Four-Hands and Narrator',
    Category: 'Piano Four-Hands',
    Forces: 'One Piano, Four-Hands and Narrator',
    dateOfComposition: '2020',
    Duration: '18.5 minutes',
    Score: '42 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/letombeaudesaintsaenspianofourhandsandnarrator',
    catalogueNo: '20c'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Piano Four-Hands and Narrator',
    Category: 'Piano Four-Hands and Narrator',
    Forces: 'One Piano, Four-Hands and Narrator',
    dateOfComposition: 'orig. 2007; arr. 2012',
    Duration: '12.5 minutes',
    Score: '27 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut-for-piano-four-hands-and-narrator',
    catalogueNo: '022 / 053'
  },
  {
    Title: 'Taylor Fanfare for Piano Four-Hands',
    Category: 'Piano Four-Hands',
    Forces: 'One Piano, Four-Hands',
    dateOfComposition: '2013',
    Duration: '4.5 minutes',
    Score: '16 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/taylor-fanfare-for-piano-four-hands?rq=taylor%20fanfare',
    catalogueNo: '054'
  },
  {
    Title: 'Twelve Great Classical Melodies From Mozart to Tchaikovsky (for the early grade piano student and their teacher to play together)',
    Category: 'Piano Four-Hands (Pedagogical)',
    Forces: 'One Piano, Four-Hands',
    dateOfComposition: '2023',
    Duration: 'not given',
    Score: 'to be added',
    partOrParts: 'n/a',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'to be added',
    catalogueNo: 'to be added'
  }
]

export const twoPianos = [
  {
    Title: 'Four Bachtatonic/Rocktatonic Inventions for Two Pianos',
    Category: 'Two Pianos',
    Forces: 'Two Pianos, Four-Hands',
    dateOfComposition: '2018',
    Duration: '11 minutes',
    Score: '37 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/bachtatonicrocktatonic-inventions-for-two-pianos',
    catalogueNo: '055'
  }
]  

export const pedPiano = [
  {
    Title: 'Twelve Short Pieces for Piano (from beginner to intermediate levels)',
    Category: 'Pedagogical Piano',
    Forces: 'Piano',
    dateOfComposition: '2023',
    Duration: 'not given',
    Score: 'to be added',
    partOrParts: 'n/a',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'to be added',
    catalogueNo: 'to be added'
  },
  {
    Title: 'Twelve Great Classical Melodies From Mozart to Tchaikovsky (for the early grade piano student and their teacher to play together)',
    Category: 'Pedagogical Piano',
    Forces: 'One Piano, Four Hands',
    dateOfComposition: '2023',
    Duration: 'not given',
    Score: 'to be added',
    partOrParts: 'n/a',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'to be added',
    catalogueNo: 'to be added'
  },
  {
    Title: '24 Erstwhile Familiar Tunes',
    Category: 'Pedagogical Piano',
    Forces: 'Piano Solo, Four-Hands, and Six-Hands',
    dateOfComposition: '2023',
    Duration: 'not given',
    Score: 'to be added',
    partOrParts: 'n/a',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'to be added',
    catalogueNo: 'to be added'
  }
]  

export const instrArrangements = [
  {
    Title: 'Aria Variata alla maniera italiana (BWV 989) by J.S. Bach / Arranged for Flute and Bassoon',
    Category: 'Instrumental Arrangements',
    Forces: 'Flute and Bassoon',
    dateOfComposition: 'arr. 2003',
    Duration: 'ca. 16 minutes',
    Score: '11 pp.',
    partOrParts: '9 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/aria-variata-alla-maniera-italiana-flute-bassoon-bach-kies',
    catalogueNo: '068'
  },
  {
    Title: 'Aria Variata alla maniera italiana (BWV 989) by J.S. Bach / Arranged for Oboe and Bassoonpiano student and their teacher to play together)',
    Category: 'Instrumental Arrangements',
    Forces: 'Oboe and Bassoon',
    dateOfComposition: 'arr. 2003',
    Duration: 'ca. 16 minutes',
    Score: '12 pp.',
    partOrParts: '9 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/aria-variata-in-a-minor-for-oboe-and-bassoon',
    catalogueNo: '069'
  },
  {
    Title: 'Children\'s Carnival, Op. 25 by Beach / Arranged for Woodwind Quartet',
    Category: 'Instrumental Arrangements',
    Forces: 'Woodwind Quartet (flute, oboe, clarinet, and bassoon)',
    dateOfComposition: 'arr. 1998; revised 2008',
    Duration: 'ca. 9 min.',
    Score: '28 pp.',
    partOrParts: '34 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/childrens-carnival-op25',
    catalogueNo: '078'
  },
  {
    Title: 'String Quartet in F Major, Op. 135 by Beethoven / Arranged for Saxophone Quartet',
    Category: 'Instrumental Arrangements',
    Forces: 'Saxophone Quartet (SATB)',
    dateOfComposition: 'arr. 2015',
    Duration: 'ca. 25 min.',
    Score: '48 pp.',
    partOrParts: '44 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/beethoven-string-quartet-in-f-major-arranged-for-saxophone-quartet',
    catalogueNo: '079'
  },
  {
    Title: 'Six Pieces from Children\'s Games, Op. 22 by Bizet / Arranged for Oboe, Bassoon and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: 'arr. 2016',
    Duration: 'ca. 12 min.',
    Score: '36 pp.',
    partOrParts: '22 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/six-pieces-from-childrens-games-op-22-by-bizet-arranged-for-oboe-bassoon-and-piano',
    catalogueNo: '081'
  },
  {
    Title: 'Seven Piano Pieces by Brahms Arranged for Bassoon and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: 'arr. 2020',
    Duration: 'ca. 21 min.',
    Score: '59 pp.',
    partOrParts: '21 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/seven-piano-pieces-of-johannes-brahms-arranged-for-bassoon-and-piano',
    catalogueNo: '082'
  },
  {
    Title: 'Five Pieces from Op. 76 by Brahms Arranged for Oboe and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Oboe and Piano',
    dateOfComposition: 'arr. 2013-14',
    Duration: 'ca. 15 min.',
    Score: '28 pp.',
    partOrParts: '9 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/five-pieces-from-op-76-by-johannes-brahms-arranged-for-oboe-and-piano',
    catalogueNo: '083'
  },
  {
    Title: 'Three Intermezzi by Brahms Arranged for Oboe and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Oboe and Piano',
    dateOfComposition: 'arr. 2014',
    Duration: 'not given.',
    Score: '17 pp.',
    partOrParts: '5 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/three-intermezzi-opus117-by-brahms-arranged-for-oboe-and-piano',
    catalogueNo: '083b'
  },
  {
    Title: 'Sixteen Pieces by Brahms Arranged for Clarinet and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Clarinet and Piano',
    dateOfComposition: 'arr. 2013',
    Duration: 'ca. 45 minutes',
    Score: '103 pp.',
    partOrParts: '46 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/sixteen-pieces-by-johannes-brahms-arranged-for-clarinet-and-piano',
    catalogueNo: '084'
  },
  {
    Title: 'Sixteen Pieces by Brahms Arranged for Clarinet and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Clarinet and Piano',
    dateOfComposition: 'arr. 2013',
    Duration: 'ca. 45 minutes',
    Score: '103 pp.',
    partOrParts: '46 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/sixteen-pieces-by-johannes-brahms-arranged-for-clarinet-and-piano',
    catalogueNo: '084'
  },
  {
    Title: 'Sixteen Piano Pieces by Brahms Arranged for Alto Saxophone and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Saxophone and Piano',
    dateOfComposition: 'arr. 2015',
    Duration: 'ca. 45 minutes',
    Score: '122 pp.',
    partOrParts: '40 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/sixteen-piano-pieces-by-brahms-arranged-for-alto-saxophone-and-piano',
    catalogueNo: '085'
  },
  {
    Title: 'Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'arr. 2017',
    Duration: 'not given',
    Score: '194 pp.',
    partOrParts: '76 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF or bound scores with parts',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/thirtypianopiecesbybrahmsarrangedforviolinandpiano',
    catalogueNo: '086'
  },
  {
    Title: 'Two Ballades from Opus 10 by Johannes Brahms for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'arr. 2015',
    Duration: 'not given',
    Score: '194 pp.',
    partOrParts: '76 pp.',
    programNoteAvailable: 'Yes; see Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/two-ballades-from-opus-10-by-johannes-brahms-for-violin-and-piano',
    catalogueNo: '086a'
  },
  {
    Title: 'Eight Pieces, Opus 76 by Johannes Brahms for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'arr. 2013-14',
    Duration: 'not given',
    Score: '41 pp.',
    partOrParts: '20 pp.',
    programNoteAvailable: 'Yes; see Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/eight-pieces-opus-76-by-johannes-brahms-for-violin-and-piano?rq=086b',
    catalogueNo: '086b'
  },
  {
    Title: 'Fantasies, Opus 116 by Johannes Brahms for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'arr. 2015',
    Duration: 'not given',
    Score: '41 pp.',
    partOrParts: '15 pp.',
    programNoteAvailable: 'Yes; see Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/fantasies-opus-116-by-johannes-brahms-for-violin-and-pian?rq=086c',
    catalogueNo: '086c'
  },
  {
    Title: 'Three Intermezzi, Op. 117 by Johannes Brahms for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'arr. 2014',
    Duration: 'not given',
    Score: '17 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Yes; see Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/three-intermezzi-opus-117-by-johannes-brahms-for-violin-and-piano?rq=086d',
    catalogueNo: '086d'
  },
  {
    Title: 'Six Pieces, Opus 118 by Johannes Brahms for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'arr. 2014',
    Duration: 'not given',
    Score: '36 pp.',
    partOrParts: '12 pp.',
    programNoteAvailable: 'Yes; see Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/six-pieces-opus-118-by-johannes-brahms-for-violin-and-piano?rq=086e',
    catalogueNo: '086e'
  },
  {
    Title: 'Four Pieces, Opus 119 by Johannes Brahms for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'arr. 2015',
    Duration: 'not given',
    Score: '31 pp.',
    partOrParts: '11 pp.',
    programNoteAvailable: 'Yes; see Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/four-pieces-opus-119-by-johannes-brahms-for-violin-and-piano?rq=opus%20119',
    catalogueNo: '086f'
  },
  {
    Title: 'Two Ballades from Opus 10 by Johannes Brahms for Viola and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Viola and Piano',
    dateOfComposition: 'arr. 2015',
    Duration: 'not given',
    Score: '28 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Yes; see Thirty Piano Pieces by Brahms Arranged for Violin and Piano',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/two-ballades-from-opus-10-by-johannes-brahms-for-viola-and-piano',
    catalogueNo: '087'
  },
  {
    Title: 'Dolly, Op. 56 by Fauré Arranged for Oboe, Bassoon, and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: 'arr. 2014',
    Duration: 'ca. 16 minutes',
    Score: '42 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3 and YouTube Video; Two Separate Live Performances',
    URL: 'https://www.christopherkies.com/store/dolly-suite-op-56-arranged-for-oboe-bassoon-and-piano',
    catalogueNo: '096'
  },
  {
    Title: 'Three Movements from Dolly: Berceuse, Mi-A-Ou, Jardin de Dolly, Op. 56 Arranged for Wind Septet',
    Category: 'Instrumental Arrangements',
    Forces: 'Wind Septet (flute, oboe, 2 clarinets, 2 bassoons, and horn)',
    dateOfComposition: 'arr. 2000',
    Duration: '8 minutes',
    Score: 'to be added',
    partOrParts: 'to be added',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'to be added',
    recordingFormat: 'n/a',
    URL: 'to be added',
    catalogueNo: 'to be added'
  },
  {
    Title: 'Five Pieces by Edward MacDowell Arranged for Alto Saxophone and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Alto Saxophone and Piano',
    dateOfComposition: 'arr. 2013',
    Duration: 'ca. 10 minutes',
    Score: '18 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/five-pieces-by-edward-macdowell-for-alto-saxophone-and-piano',
    catalogueNo: '099'
  },
  {
    Title: 'Five Pieces by Edward MacDowell Arranged for Alto Saxophone and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Alto Saxophone and Piano',
    dateOfComposition: 'arr. 2013',
    Duration: 'ca. 10 minutes',
    Score: '18 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/five-pieces-by-edward-macdowell-for-alto-saxophone-and-piano',
    catalogueNo: '099'
  },
  {
    Title: 'Five Pieces by Edward MacDowell Arranged for Clarinet in B Flat and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Clarinet in B-flat and Piano',
    dateOfComposition: 'arr. 2013',
    Duration: 'ca. 10 minutes',
    Score: '18 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/five-pieces-by-edward-macdowell-arranged-for-clarinet-and-piano',
    catalogueNo: '100'
  },
  {
    Title: 'Three Pieces by Edward MacDowell Arranged for Woodwind Quartet',
    Category: 'Instrumental Arrangements',
    Forces: 'Woodwind Quartet (flute, oboe, clarinet, and bassoon)',
    dateOfComposition: 'arr. 2000; revised 2009',
    Duration: 'ca. 6 minutes',
    Score: '15 pp.',
    partOrParts: '20 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/three-pieces-by-edward-macdowell-arranged-for-woodwind-quartet',
    catalogueNo: '101'
  },
  {
    Title: 'Elite Syncopations by Scott Joplin Arranged for (mixed) Clarinet Quartet',
    Category: 'Instrumental Arrangements',
    Forces: 'Mixed Clarinet Quartet (3 clarinets in b-flat, 1 bass clarinet)',
    dateOfComposition: 'arr. 2018',
    Duration: '3 minutes',
    Score: '7 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/elite-syncopations-arranged-for-clarinet-quartet',
    catalogueNo: '103'
  },
  {
    Title: 'Sonata in B Major, Op. 147 by Franz Schubert Arranged for Oboe and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Oboe and Piano',
    dateOfComposition: 'arr. 2017',
    Duration: '25 minutes',
    Score: '33 pp.',
    partOrParts: '11 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/sonata-in-b-op-147-by-schubert-arranged-for-oboe-and-piano',
    catalogueNo: '104'
  },
  {
    Title: 'Fantasie, Opus 17 by Robert Schumann (III. Langsam getragen. Durchweg leise zu halten) Adapted for Violin and Piano',
    Category: 'Instrumental Arrangements',
    Forces: 'Violin and Piano',
    dateOfComposition: 'adapted 2022',
    Duration: 'not given',
    Score: '13 pp.',
    partOrParts: '4 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/fantasie-opus-17-robert-schumann-violin-piano-adaptation-christopher-kies',
    catalogueNo: '147'
  },
  {
    Title: 'Kinderszenen, Op. 15 by Robert Schumann Arranged for Woodwind Quartet',
    Category: 'Instrumental Arrangements',
    Forces: 'Woodwind Quartet (flute, oboe, clarinet, and bassoon)',
    dateOfComposition: 'arr. 2021',
    Duration: '18 minutes',
    Score: '36 pp.',
    partOrParts: '56 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/kinderszenen-by-robert-schumann-arranged-for-woodwind-quartet',
    catalogueNo: '105'
  }
]  

export const soloVoiceAndAccomp = [
  {
    Title: 'Karen\'s Song for Soprano (or Treble Chorus), Flute and Piano (or Harp)',
    Category: 'Solo Voice and Accompaniment',
    Forces: 'Soprano (or Treble Chorus), Flute, and Piano (or Harp)',
    dateOfComposition: '2003',
    Duration: '2.5 minutes',
    Score: '6 pp.',
    partOrParts: '2 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/karens-song-for-soprano-or-treble-chorus-flute-and-piano-or-harp',
    catalogueNo: '109'
  },
  {
    Title: 'Six Italian Songs for Soprano and Piano',
    Category: 'Solo Voice and Accompaniment',
    Forces: 'Soprano and Piano',
    dateOfComposition: '2013',
    Duration: '13 minutes',
    Score: '33 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/six-italian-song-for-soprano-and-piano',
    catalogueNo: '112'
  },
]

export const twoOrMoreVoicesAndAccomp = [
  {
    Title: 'Chinese Folk Song Mashup 1.0',
    Category: 'Two or More Voices and Accompaniment',
    Forces: 'Four Solo Singers (SATB), Piano, and Woodwind Quartet',
    dateOfComposition: '2017',
    Duration: '4.75 minutes',
    Score: 'Full Score: 25 pp. + Piano/Vocal Score: 13 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/chinese-folk-song-mashup-10',
    catalogueNo: '114'
  }
]  