export const concertos = [
  {
    Title: 'Academic Festival Rag for Piano and Wind Ensemble',
    Category: 'Concertos',
    Forces: 'Piano and Wind Ensemble',
    dateOfComposition: '2012',
    Duration: '10.5 minutes',
    Score: '61 pp.',
    partOrParts: '163 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/academic-festival-rag-for-piano-and-wind-ensemble',
    catalogueNo: '001'
  },
  {
    Title: 'Academic Festival Rag for Two Pianos',
    Category: 'Concertos',
    Forces: 'Two Pianos',
    dateOfComposition: '2012',
    Duration: '10.5 minutes',
    Score: '32 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/academic-festival-rag-for-two-pianos',
    catalogueNo: '002'
  },
  {
    Title: 'Introduction and Ragtime for Clarinet in B-flat and Piano',
    Category: 'Concertos',
    Forces: 'Clarinet in B-flat and Piano',
    dateOfComposition: '2012',
    Duration: '9.25 minutes',
    Score: '19 pp.',
    partOrParts: '7 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/introduction-and-rag-for-clarinet-and-orchestra-arranged-for-clarinet-and-piano',
    catalogueNo: '004'
  }
]

export const orchestral = [
  {
    Title: 'Franklin Portrait: Preamble for Orchestra',
    Category: 'Orchestra',
    Forces: 'Orchestra',
    dateOfComposition: '2006',
    Duration: '5 minutes',
    Score: '22 pp.',
    partOrParts: '57 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/franklin-portrait-preamble-for-orchestra',
    catalogueNo: '007'
  }
]

export const orchestraNarration = [
  {
    Title: 'Le Tombeau de Saint-Saëns',
    Category: 'Orchestra with Narration',
    Forces: 'Orchestra and Narrator',
    dateOfComposition: '2003',
    Duration: '23.5 minutes',
    Score: '115 pp.',
    partOrParts: '336 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-orchestra-and-narrator',
    catalogueNo: '010'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut)',
    Category: 'Orchestra with Narration',
    Forces: 'Orchestra and Narrator',
    dateOfComposition: '2008',
    Duration: '13 minutes',
    Score: '45 pp.',
    partOrParts: '88 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut-for-orchestra-and-narrator',
    catalogueNo: '011'
  }
]

export const concertBandNarration = [
  {
    Title: 'Little Red Riding Hood or Ladle Rat Rotten Hut for Concert Band and Narrator',
    Category: 'Concert Band with Narration',
    Forces: 'Concert Band and Narrator',
    dateOfComposition: '2009',
    Duration: '12.5 minutes',
    Score: '51 pp.',
    partOrParts: '89 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/littleredridinghoodforconcertbandnarrator',
    catalogueNo: '014'
  }
]

export const chamberEnsemblesNarration = [
  {
    Title: 'Le Tombeau de Saint-Saëns for Woodwind Quintet and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Woodwind Quintet and Narrator',
    dateOfComposition: '2013',
    Duration: '18.5 minutes',
    Score: '43 pp.',
    partOrParts: '91 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-woodwind-quintet-and-narrator',
    catalogueNo: '020'
  },
  {
    Title: 'Le Tombeau de Saint-Saëns for Marimba, Clarinet in B flat, Piano and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Marimba, Clarinet in B-flat, Piano, and Narrator',
    dateOfComposition: '2020',
    Duration: '18.5 minutes',
    Score: '36 pp.',
    partOrParts: '29 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-marimba-clarinet-in-b-flat-piano-and-narrator',
    catalogueNo: '020b'
  },
  {
    Title: 'Le Tombeau de Saint-Saëns for Piano Four-Hands and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Piano Four-Hands and Narrator',
    dateOfComposition: '2020',
    Duration: '18.5 minutes',
    Score: '42 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI excerpts for nos. 1, 4, 10, and 13',
    URL: 'https://www.christopherkies.com/store/letombeaudesaintsaenspianofourhandsandnarrator',
    catalogueNo: '020c'
  },
  {
    Title: 'Le Tombeau de Saint-Saëns for Brass Quintet and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Brass Quintet and Narrator',
    dateOfComposition: '2002, rev. 2009',
    Duration: '18.5 minutes',
    Score: '46 pp.',
    partOrParts: '83 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/le-tombeau-de-saint-saens-for-brass-quintet-and-narrator',
    catalogueNo: '021'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Piano Four-Hands and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Piano Four-Hands and Narrator',
    dateOfComposition: '2007; arr. for piano four-hands in 2012',
    Duration: '12.5 minutes',
    Score: '27 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI (no narrator)',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut-for-piano-four-hands-and-narrator',
    catalogueNo: '022 / 053'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Oboe, Bassoon, Piano, and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Oboe, Bassoon, Piano, and Narrator',
    dateOfComposition: '2007',
    Duration: '12.5 minutes',
    Score: '25 pp.',
    partOrParts: '10 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Recording',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut-for-oboe-bassoon-and-piano',
    catalogueNo: '023'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Flute, Bassoon, Piano and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Flute, Bassoon, Piano, and Narrator',
    dateOfComposition: '2007',
    Duration: '12.5 minutes',
    Score: '25 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-for-flute-bassoon-piano-and-narrator',
    catalogueNo: '024'
  },
  {
    Title: 'Little Red Riding Hood (or Ladle Rat Rotten Hut) for Clarinet in B Flat, Cello, Piano, and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Clarinet in B-flat, Cello, Piano, and Narrator',
    dateOfComposition: '2007',
    Duration: '12.5 minutes',
    Score: '27 pp.',
    partOrParts: '11 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/little-red-riding-hood-or-ladle-rat-rotten-hut',
    catalogueNo: '026'
  },
  {
    Title: 'Old Business for Piano, Contrabass, Drum Set, and Narrator',
    Category: 'Chamber Ensembles with Narration',
    Forces: 'Piano, Contrabass, Drum Set, and Narrator',
    dateOfComposition: '2012',
    Duration: '11 minutes',
    Score: '68 pp.',
    partOrParts: '16 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/old-business',
    catalogueNo: '027'
  }
]

export const chamberMusicDoubleReed = [
  {
    Title: 'Arietta for Bassoon Quartet',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Four Bassoons',
    dateOfComposition: '2007',
    Duration: '4 minutes',
    Score: '7 pp.',
    partOrParts: '8 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/arietta-for-bassoon-quartet',
    catalogueNo: '028'
  },
  {
    Title: 'Four Bachtatonic/Rocktatonic Inventions for Oboe, Clarinet in B flat and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Clarinet in B-flat, and Piano',
    dateOfComposition: '2018',
    Duration: '10.5 minutes',
    Score: '37 pp.',
    partOrParts: '16 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/four-bachtatonicrocktatonic-inventions-for-oboe-clarinet-in-b-flat-and-piano',
    catalogueNo: '029'
  },
  {
    Title: 'In-Two-itive Dances for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2002',
    Duration: '12 minutes',
    Score: '44 pp.',
    partOrParts: '19 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/e0lteemsvsyzt2ybrqa7q3hk417352',
    catalogueNo: '030'
  },
  {
    Title: 'Nobody Knows for Oboe and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe and Piano',
    dateOfComposition: '2013',
    Duration: '6 minutes',
    Score: '23 pp.',
    partOrParts: '5 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/nobody-knows-for-oboe-and-piano',
    catalogueNo: '032'
  },
  {
    Title: 'The Octatonic Rag for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2010',
    Duration: '4.5 minutes',
    Score: '16 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/octatonic-rag-for-oboe-bassoon-and-piano',
    catalogueNo: '034b'
  },
  {
    Title: 'Sieben Lieder ohne Wörter (aus Des Knaben Wunderhorn) for Bassoon and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Bassoon and Piano',
    dateOfComposition: '2014',
    Duration: '14 minutes',
    Score: '34 pp.',
    partOrParts: '12 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/sieben-lieder-ohne-worter-aus-des-knaben-wunderhorn-for-bassoon-and-piano',
    catalogueNo: '043'
  },
  {
    Title: 'Sonata for Bassoon and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Bassoon and Piano',
    dateOfComposition: '2003; revised 2007',
    Duration: '13.5 minutes',
    Score: '30 pp.',
    partOrParts: '10 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/sonata-for-bassoon-and-piano',
    catalogueNo: '044'
  },
  {
    Title: 'Take the Love, This Can\'t Be the A Train for Bassoon Quartet',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Four Bassoons',
    dateOfComposition: '2010',
    Duration: '4.25 minutes',
    Score: '14 pp.',
    partOrParts: '12 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/take-the-love-this-cant-be-the-a-train-for-bassoon-quartet',
    catalogueNo: '045'
  },
  {
    Title: 'Take the Love, This Can\'t Be the A Train for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2010',
    Duration: '4.5 minutes',
    Score: '15 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/take-the-love-this-cant-be-the-a-train',
    catalogueNo: '046'
  },
  {
    Title: 'Taylor Fanfare for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2013',
    Duration: '4.5 minutes',
    Score: '17 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/taylor-fanfare-for-oboe-bassoon-and-piano',
    catalogueNo: '047'
  },
  {
    Title: 'Variations on Country Gardens for Woodwind Quartet',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2005 and 2012',
    Duration: '3 minutes',
    Score: '10 pp.',
    partOrParts: '12 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/variations-on-country-gardens-for-woodwind-quartet',
    catalogueNo: '048'
  },
  {
    Title: 'Variations on Country Gardens for Oboe, Bassoon, and Piano',
    Category: 'Chamber Music with Double Reed Instruments',
    Forces: 'Oboe, Bassoon, and Piano',
    dateOfComposition: '2005 and 2012',
    Duration: '3 minutes',
    Score: '13 pp.',
    partOrParts: '6 pp.',
    programNoteAvailable: 'Short Description',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3, Live Performance',
    URL: 'https://www.christopherkies.com/store/variations-on-country-gardens',
    catalogueNo: '049'
  }
]

export const otherInstrumental = [
  {
    Title: 'Flight of the Bungled G for Harpsichord',
    Category: 'Other Instrumental Works',
    Forces: 'Harpsichord',
    dateOfComposition: '2001',
    Duration: '2.5 minutes',
    Score: '8 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/flight-of-the-bungled-g-for-harpsicord',
    catalogueNo: '144'
  },
  {
    Title: 'Four Bachtatonic/Rocktatonic Inventions for Marimba, Clarinet in B Flat, and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'Marimba, Clarinet in B-flat, and Piano',
    dateOfComposition: '2018',
    Duration: '11 minutes',
    Score: '35 pp.',
    partOrParts: '16',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/four-bachtatonicrocktatonic-inventions-for-marimba-clarinet-in-b-flat-and-piano',
    catalogueNo: '056'
  },
  {
    Title: 'Ragtime Reflections for Flute and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'Flute and Piano',
    dateOfComposition: '2013',
    Duration: 'not given',
    Score: '13 pp.',
    partOrParts: '4',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/ragtime-reflections-flute-and-piano',
    catalogueNo: '061'
  },
  {
    Title: 'Take the Love, This Can\'t be the A Train for Clarinet in B Flat and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'Clarinet in B-flat and Piano',
    dateOfComposition: '2010; revised 2011',
    Duration: '4.5 minutes',
    Score: '12 pp.',
    partOrParts: '3',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performance',
    URL: 'https://www.christopherkies.com/store/take-the-love-this-cant-be-the-a-train-for-clarinet-in-b-flat-and-piano',
    catalogueNo: '063'
  },
  {
    Title: 'Taylor Fanfare for String Quartet and Piano',
    Category: 'Other Instrumental Works',
    Forces: 'String Quartet and Piano',
    dateOfComposition: 'orig. 2013; arr. 2017',
    Duration: '4.5 minutes',
    Score: '24 pp.',
    partOrParts: '12',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'n/a',
    URL: 'https://www.christopherkies.com/store/taylor-fanfare-for-string-quartet-and-piano',
    catalogueNo: '066'
  }
]

export const pianoSolo = [
  {
    Title: 'Eight Ragtime Pieces for Piano',
    Category: 'Piano Solo',
    Forces: 'Piano',
    dateOfComposition: '1975-1993',
    Duration: 'ca. 28 minutes',
    Score: '81 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'Yes',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; Live Performances',
    URL: 'https://www.christopherkies.com/store/eight-ragtime-pieces-for-piano',
    catalogueNo: '051'
  },
  {
    Title: 'Cadenzas to W. A. Mozart\'s Piano Concerto, K. 467',
    Category: 'Piano Solo',
    Forces: 'Piano',
    dateOfComposition: '1980; revised 2021',
    Duration: 'not given',
    Score: '11 pp.',
    partOrParts: 'n/a',
    programNoteAvailable: 'n/a',
    sheetMusicFormat: 'PDF',
    recordingFormat: 'mp3; MIDI',
    URL: 'https://www.christopherkies.com/store/cadenzas-to-mozarts-piano-concerto-k-467',
    catalogueNo: '146'
  }
]